import Head from "next/head";
import React from "react";

const MetaHead: React.FC<{
  children?: string | string[];
}> = ({ children }) => {
  return (
    <Head>
      <title>{children || "Slack Clone"}</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default MetaHead;
